import type { Metadata } from 'next';
import { Breadcrumbs } from '@/components/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Terms of Service — Email Tools Pro',
  description: 'Email Tools Pro Terms of Service. Read our terms before using our free email tools.',
  alternates: { canonical: 'https://emailtoolspro.com/terms-of-service' },
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <Breadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Terms of Service' }]} />

      <h1 className="text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
      <p className="text-sm text-muted mb-8">Last updated: January 1, 2025</p>

      <div className="prose max-w-none space-y-8">

        <section>
          <h2>Agreement to Terms</h2>
          <p>
            By accessing and using Email Tools Pro (&quot;Service&quot;) at emailtoolspro.com, you agree to be bound by these
            Terms of Service. If you disagree with any part of these terms, you may not access the Service.
          </p>
        </section>

        <section>
          <h2>Use of Service</h2>
          <h3>Permitted Uses</h3>
          <ul>
            <li>Using tools for personal email management and organization</li>
            <li>Using tools for legitimate business email operations</li>
            <li>Software development and testing</li>
            <li>Educational purposes</li>
            <li>Email marketing to opted-in recipients in compliance with applicable laws</li>
          </ul>

          <h3>Prohibited Uses</h3>
          <ul>
            <li>Sending unsolicited commercial email (spam) using addresses generated by our tools</li>
            <li>Creating fraudulent accounts or impersonating individuals or organizations</li>
            <li>Harvesting email addresses for spam or malicious purposes</li>
            <li>Circumventing platform terms of service using our tools</li>
            <li>Any use that violates applicable laws, including CAN-SPAM, GDPR, and CASL</li>
            <li>Automated scraping of our website without permission</li>
          </ul>
        </section>

        <section>
          <h2>Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality are owned by Email Tools Pro
            and are protected by international copyright, trademark, and other intellectual property laws.
          </p>
          <p>
            Results generated by our tools (email addresses, username suggestions, etc.) are not
            owned by us — they are generated based on your inputs and are yours to use within the
            bounds of these terms.
          </p>
        </section>

        <section>
          <h2>Disclaimer of Warranties</h2>
          <p>
            The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis without any warranties of any kind,
            either express or implied. We do not warrant that:
          </p>
          <ul>
            <li>The Service will be uninterrupted or error-free</li>
            <li>Results from our tools are 100% accurate (e.g., our disposable email database may be incomplete)</li>
            <li>The Service will meet your specific requirements</li>
          </ul>
        </section>

        <section>
          <h2>Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Email Tools Pro shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages resulting from your use of the Service,
            including but not limited to:
          </p>
          <ul>
            <li>Inaccurate validation results</li>
            <li>Loss of data or business opportunities</li>
            <li>Decisions made based on tool outputs</li>
          </ul>
        </section>

        <section>
          <h2>Email Laws Compliance</h2>
          <p>
            If you use our tools in connection with email marketing or outreach, you are solely responsible
            for compliance with all applicable email laws, including:
          </p>
          <ul>
            <li><strong>CAN-SPAM Act</strong> (United States)</li>
            <li><strong>GDPR</strong> (European Union)</li>
            <li><strong>CASL</strong> (Canada)</li>
            <li>Other applicable regional email regulations</li>
          </ul>
        </section>

        <section>
          <h2>Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. We will provide notice of significant
            changes by updating the &quot;Last updated&quot; date. Continued use after changes constitutes acceptance.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            Questions about these Terms? <a href="/contact" className="text-primary hover:underline">Contact us</a>.
          </p>
        </section>

      </div>
    </div>
  );
}
