import type { Metadata } from 'next';
import { ToolWrapper } from '@/components/ToolWrapper';
import { RandomGmailGeneratorTool } from './RandomGmailGeneratorTool';

export const metadata: Metadata = {
  title: 'Random Gmail Generator — Generate Random Gmail-Style Addresses',
  description:
    'Generate random Gmail-style email addresses instantly. Create bulk random emails for testing, placeholders, or inspiration. Free with one-click copy.',
  keywords: ['random gmail generator', 'random email generator', 'fake gmail generator', 'random email address'],
  alternates: { canonical: 'https://emailtoolspro.com/tools/random-gmail-generator' },
};

export default function RandomGmailGeneratorPage() {
  return (
    <>
      <ToolWrapper
        title="Random Gmail Generator"
        description="Generate realistic random Gmail-style addresses for testing, placeholders, or inspiration. Choose from different naming styles and batch sizes."
        toolName="Random Gmail Generator"
      >
        <RandomGmailGeneratorTool />
      </ToolWrapper>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="prose max-w-none">
          <h2>Why Generate Random Gmail Addresses?</h2>
          <p>
            Random Gmail address generators are useful for <strong>software testing</strong>, creating placeholder data,
            database seeding, UI mockups, and anywhere you need realistic-looking email addresses without using real ones.
          </p>
          <h3>Important Note</h3>
          <p>
            The addresses generated by this tool are <strong>not real Gmail accounts</strong> — they are generated to look
            realistic but do not correspond to actual mailboxes. Never use generated emails to impersonate real people.
          </p>
        </div>
      </div>
    </>
  );
}
